org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

moddev_version=2.0.141

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.68-beta
neo_version_range=[26.1.2.68-beta,)
loader_version_range=[1,)

mod_id=scanner_cache
mod_name=Scanner Cache Mixins
mod_license=CC0-1.0
mod_version=1.0.0
mod_group_id=com.alonie.cache
archives_base_name=cachedeval-neoforge-26.1.2
mod_authors=Alonie
mod_description=Per-tick caching for NbtPredicate.getEntityTagToCompare() and EntityPredicate.matches() to eliminate duplicate serialization overhead.
